CREATE TABLE IF NOT EXISTS statistic_records
(
    statistic_record_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_name text,
    ip TEXT,
    uri TEXT,
    timestamp TIMESTAMP
);